#!/usr/bin/env bash

srcH() {
  if [[ -z "$1" ]]; then
      FILE="default"
  else
    FILE="$1"
  fi

  if [[ -f "$SCRIPT_DIR/$FILE" ]]; then
    echo "Sourcing $SCRIPT_DIR/$FILE"
    # shellcheck source=/dev/null
    . "$SCRIPT_DIR/$FILE"
  else
    echo "File not found: $SCRIPT_DIR/$FILE"
  fi
}
