#!/usr/bin/env bash

alias redisflush="redis-cli flushall"
alias redisstart="brew services start redis"
alias redisstop="brew services stop redis"

helpredis() {
    echo 'The following commands are available to assist you with Redis:'
    echo '    redisflush: Flushes all keys from the Redis database `redis-cli flushall`'
    echo '    redisstart: Starts the Redis service `brew services start redis`'
    echo '    redisstop: Stops the Redis service `brew services stop redis`'
}
